### ISSUE TITLE
Containers can lose their DHCP lease when dhclient is used

### ISSUE THREAD

**Issue by rtkrruvinskiy** [jpetazzo/pipework#111]
As a result of https://github.com/jpetazzo/pipework/commit/0f59dc4007b4473ff61e6057505ffc114cfec8d0, dhclient is killed immediately after container start-up, which means that when the DHCP lease expires, the container will never renew it, opening up the IP for reassignment (and removing dynamically created DNS entries, if any). I'm not sure why only dhclient is being killed and the other DHCP clients aren't. Is it possible to not kill dhclient and instead solve the original contributor's problem some other way?

**Comment by jpetazzo** [comment]
The new DHCP mechanism should fix this, so I'm closing this issue. Thanks!
