### ISSUE TITLE
How to set coreos host to communicate via macvlan to talk to containers

### ISSUE THREAD

**Issue by brettnem** [jpetazzo/pipework#112]
Hello,
I realize this is probably more of a coreos issue, but I can't find anyone in that community that can answer this. My host machines running docker are core os. How would I structure my unit files for the networking such that I can both provision those host interfaces with DHCP and allow them to communicate to the containers?

Thanks!
-Brett

**Comment by jpetazzo** [comment]
Hi Brett,

I honestly have no idea. If you're still struggling with this, can you describe what you're trying to do?

Best,

**Comment by jpetazzo** [comment]
Closing older issues.
