### ISSUE TITLE
dhcp ip from bridge with dnsmasq: container can't be found via host name

### ISSUE THREAD

**Issue by ovanes** [jpetazzo/pipework#114]
For simplicity I just used an `lxcbr0` to get IPs managed by DHCP server. It seems like the container started with:

    sudo docker run --name=test_container4 -h test_container4 --net="none"  --rm -ti optobee/server-template:0.0.2 /sbin/my_init -- bash -l

and later on created a new network interface with `pipework`:

    sudo ./pipework lxcbr0 -i eth0 test_container4 dhcp

`ip a` shows a newly created interface:

    100: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
        link/ether 46:26:0d:40:d5:d1 brd ff:ff:ff:ff:ff:ff
        inet 10.0.3.13/24 brd 10.0.3.255 scope global eth0
           valid_lft forever preferred_lft forever
        inet6 fe80::4426:dff:fe40:d5d1/64 scope link
           valid_lft forever preferred_lft forever

but the host has no clue about it:

    $ ping test_container4
    ping: unknown host test_container4

    $ host test_container4 10.0.3.1
    Using domain server:
    Name: 10.0.3.1
    Address: 10.0.3.1#53
    Aliases:
    
    Host test_container4 not found: 3(NXDOMAIN)

Any help would be great :)

**Comment by jpetazzo** [comment]
Hi! Sorry for the slow answer... For some reason I had never seen the email notification for this issue.

I will keep this in mind for future versions of pipework, thank you!
