### ISSUE TITLE
The container cannot obtain the IP address from my router via DHCP

### ISSUE THREAD

**Issue by wood1986** [jpetazzo/pipework#115]
Host OS: CentOS 7.0
Docker: 1.3.2
Docker image: centos:latest

when I execute `pipework enp0s3 $(cat centos.cid) dhcp`, it shows the followings
`which: no udhcpc in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)`
`which: no dhcpcd in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)`
and the IP of the container does not get assigned.

**Comment by hookenz** [comment]
You need to install the package that contains either dhcpcd or udhcpc.  On Ubuntu it's normally there by default.  But, if it's not then "sudo apt-get install dhcpcd".  On CentOS systems "sudo yum install dhcp".

**Comment by wood1986** [comment]
i did install dhcp on both host and container but the container still cannot obtain the IP address from my router

**Comment by hookenz** [comment]
Is there a dhcpcd in one of the paths listed in the pipework error that your originally posted?
If not, resolve that and it should work.

**Comment by wood1986** [comment]
yes! there is with the same error. I did find dhcpcd with `find / -name dhcpcd` and nothing's found. I also did `yum whatprovides dhcpcd` and nothing's found

**Comment by kikitux** [comment]
yum search dhcp

sometimes is dhcp-client

**Comment by wood1986** [comment]
Still nothing. Here is result of `yum search dhcp`. All packages ended with x86_64 have been installed

`dhcp-common.x86_64 : Common files used by ISC dhcp client and server
dhcp-devel.i686 : Development headers and libraries for interfacing to the DHCP server
dhcp-devel.x86_64 : Development headers and libraries for interfacing to the DHCP server
dhcp-libs.i686 : Shared libraries used by ISC dhcp client and server
dhcp-libs.x86_64 : Shared libraries used by ISC dhcp client and server
dhclient.x86_64 : Provides the ISC DHCP client daemon and dhclient-script
dhcp.x86_64 : Dynamic host configuration protocol software
dnsmasq.x86_64 : A lightweight DHCP/caching DNS server
dnsmasq-utils.x86_64 : Utilities for manipulating DHCP server leases`

**Comment by kikitux** [comment]
On Wed, Jan 14, 2015 at 3:26 PM, WooD <notifications@github.com> wrote:

> dhclient.x86_64 : Provides the ISC DHCP client daemon and dhclient-script


this one

dhclient.x86_64 : Provides the ISC DHCP client daemon and dhclient-script

**Comment by wood1986** [comment]
Thanks kikitux!! I created a sym link for `dhclient-script` and now it just shows `which: no udhcpc in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)`. But the IP of the container does not get assigned by the router.

**Comment by starkovv** [comment]
@wood1986 did you resolve your issue?

**Comment by wood1986** [comment]
No

**Comment by jpetazzo** [comment]
Can you try with the latest version (to make sure that we are trying with the exact same code) and copy the exact, full output?

Thank you!

**Comment by wood1986** [comment]
Finally, I make it. Actually I run it on an existing physical interface `enp0s3` which has the ip already. So it does not work. Then I follow [Introduction to Open vSwitch (OVS)](https://www.youtube.com/watch?v=rYW7kQRyUvA) to create a bridge. Then I run `./pipework <my bridge name> $CONTAINER dhclient`.
