### ISSUE TITLE
Can pipework make DHCP work for Container in VM?

### ISSUE THREAD

**Issue by fansgit** [jpetazzo/pipework#120]
e.g. machine 1: router as DHCP Server <---> machine 2: Container in VM
finally, all the 4 boxes (machine1, machine2, VM, Container) should settle down on the same private subnet by dhcp

**Comment by jpetazzo** [comment]
Hi!

Sorry for taking so long to get back to you. The answer is "yes!"

Here is an example running a PXE (therefore, DHCP) server in a container: https://github.com/jpetazzo/pxe

HTH,
