### ISSUE TITLE
pipework add eth0, my container can lost default gateway. 

### ISSUE THREAD

**Issue by epiphyllum** [jpetazzo/pipework#123]
Problem is as follow
1.   I docker run my container with parameter --net=none
2.   I use pipework add eth0 to my container
3.   netstat -nr,    the container does not container  a default gateway,  nor can I add it,  so my container can not access the internet. 

so  how can not use pipework to add interface, in the meantime , make my container has the access to the internet ?

![55bce17c-cfc4-40ad-8af6-9d028c7d1581](https://cloud.githubusercontent.com/assets/8348065/6498064/5133990c-c322-11e4-8b2a-cda12964bdb6.png)

**Comment by pierrecdn** [comment]
Hi, 
RTFM ! https://github.com/jpetazzo/pipework#default_gateway
The syntax to add a gateway is ip/mask@gateway. 

So, with the following, you should succeed: 
```bash
pipework docker0 -i eth0 tt 172.17.0.188/24@172.17.0.1
```
