### ISSUE TITLE
Permission Denied when running pipework as a cron job

### ISSUE THREAD

**Issue by sohailalam2** [jpetazzo/pipework#125]
I was trying to use pipework to bind a docker container with a given interface and ip address on startup. This worked fine when run as a root user, but failed to work when I set up a cronjob (even as a root).

**cannot open network namespace "16324": Permission denied**

After a lot of research, I found a solution - 

It turns out that SE Linux was enforcing some rule, so had to turn it off.

so running **setenforce 0** and restarting docker service, worked for me!

**Comment by jpetazzo** [comment]
I think it's just a default SELinux policy that prevents to manipulate some system objects from a cron job.

I'll close this issue, but thanks a lot for reporting it, that's very useful!
