### ISSUE TITLE
Cannot change the container's dns informations through DHCP.

### ISSUE THREAD

**Issue by AJNOURI** [jpetazzo/pipework#127]
I use one container as a DHCP server to assign IP and DNS inf. to other containers connected to the same host bridge int.

**sudo pipework br4 -i eth1 $CID dhcp**
```initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused```
``` * Reloading /etc/samba/smb.conf smbd ```
```   ...done. ```

The client container ***eth1*** get asigned an ip address, but not dns informations (/etc/resolv.conf still holds old inf. 8.8.8.8). 
And all attempts to release and get reassigned ip failed from the container:

**root @ f1de9e5b5528:# sudo dhclient eth1 -r**
```Failed to send flush request: Operation not permitted```

**root @ f1de9e5b5528:# sudo dhclient eth1**
```RTNETLINK answers: Operation not permitted```
```RTNETLINK answers: Operation not permitted```
```mv: cannot move '/etc/resolv.conf.dhclient-new.188' to '/etc/resolv.conf': Device or resource busy```

----------------------------------------------------------------------

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

Docker version 1.5.0, build a8a31ef

**Comment by AJNOURI** [comment]
Is there any known issues related to DHCP and DNS assignments (/etc/resolv.conf)? 
Any guidance is appreciated.

**Comment by jpetazzo** [comment]
The main issue is that `/etc/resolv.conf` is not a normal file, but a bind-mount from outside the container. It's still writable, though, so a well-informed DHCP client could write to that file instead of trying to overwrite it with another file.
