### ISSUE TITLE
pipework --wait not working in container

### ISSUE THREAD

**Issue by santosh0705** [jpetazzo/pipework#128]
Im using pipework to create one new interface and give static ip address to my container and its working perfectly. But pipework --wait does not work inside container. I tried to figure it out and found the symbolic link for eth1 in /sys/class/net is not created.

I'm using self created CentOS 6.6 image running on a CentOS 6.6 virtual machine.

FYI: I've already updated iproute package with netns support in host OS. Also tried updating the same in container before running pipework but didn't help.

**Comment by santosh0705** [comment]
It worked....
thanks

**Comment by jpetazzo** [comment]
Great! Thanks for the feedback. That helps a lot!
