### ISSUE TITLE
REST API for pipework

### ISSUE THREAD

**Issue by cmanzana** [jpetazzo/pipework#131]
Hi,

I am thinking it would be great to make pipework a first class citizen in the DCOS (data-center operating system) concept.
For this to happen I believe the first step would be to have a REST API on top of pipework that would allow orchestrators to manipulate pipework remotely.

I am eager to work on such REST API, now the question is:
- do you want to have the REST API as part of your current project?
- or do you prefer that an independent project is created to provide the REST API?

cheers!

**Comment by jpetazzo** [comment]
Hi,

That would be a great idea, but implementing a REST API in shell will be tricky :-)

I think it would be better if it were a separate project. Maybe you'd love to coordinate with @pierrecdn, whose PR #122 also has a lot of great stuff?

**Comment by hookenz** [comment]
Looks like people want pipework is growing way beyond a simple tool!

**Comment by jpetazzo** [comment]
Out of curiosity - would you use this in conjunction with Docker, or with other container systems?

**Comment by dreamcat4** [comment]
Or you could use the official docker REST api / toolset, to control a pipework docker container. e.g. my `dreamcat4/pipework` image... e.g. `docker start pipework`, etc. That's what I've been doing.

Eventually we would prefer all the features of pipework to be implemented as a part docker itself. All the L2 bridge-mode networking & OVS stuff. There is an ongoing effort to do that amongst other docker teams.

So maybe it's not a long lifetime to rely upon a specific pipework API (i.e. for production systems) that will need to replace later on with something else (of official Docker networking feature). But my all means please don't let me stop you! :)
