### ISSUE TITLE
Question: kill the dhcp processes after getting IP, how to handle renews ?

### ISSUE THREAD

**Issue by zenvdeluca** [jpetazzo/pipework#133]
Hi,

noticed that pipework kills the dhcp client after configuring the IP.
My question is: how is this assuring the DHCP release renews, and avoiding the same IP being provided again to other container after lease expired ? 

the code comment is not really clear on explaining the good reason for killing the client.
thank you

 # kill dhclient after get ip address to prevent device be used after container close
        ip netns exec $NSPID $DHCP_CLIENT -pf "/var/run/dhclient.$NSPID.pid" $CONTAINER_IFNAME
        kill "$(cat "/var/run/dhclient.$NSPID.pid")"
        rm "/var/run/dhclient.$NSPID.pid"

**Comment by jpetazzo** [comment]
Hi!

You're right, `pipework` does *not* handle renews. This was a difficult decision: either we kill the DHCP client, and things are "clean" (but we don't renew the lease!) or we leave the DHCP client up and running, but then it has to be killed explicitly when getting rid of the container.

There is a new method now, thanks to `--net container:...`, it should be possible to run the DHCP client in a special-purpose container.

That would be for a future version of pipework :-)
