### ISSUE TITLE
Pipework + VRRPd

### ISSUE THREAD

**Issue by calh** [jpetazzo/pipework#139]
Hello,

I'm not sure this really qualifies as an issue, but I'm attempting to use pipework along with vrrpd to do high availability between containers.  So far, this is my test case:

```
host# docker run -ti --privileged debian
host# pipework eth0 -i eth1 1234 0/0
1234#  ifconfig eth1
eth1      Link encap:Ethernet  HWaddr 0a:46:66:e3:5f:31  
          inet6 addr: fe80::846:66ff:fee3:5f31/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2381 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:215322 (210.2 KiB)  TX bytes:830 (830.0 B)
1234#  strace -f vrrpd -i eth1 -v 100 192.168.1.2
   ...
socket(PF_INET, SOCK_DGRAM, IPPROTO_IP) = 3
ioctl(3, SIOCGIFADDR, {ifr_name="eth1", ???}) = -1 EADDRNOTAVAIL
    (Cannot assign requested address)
close(3)                                = 0
write(2, "no interface found!\n", 20no interface found!
```

I can manually assign an address to eth1 and it works correctly.  Any idea on why the `ioctl()` call fails?

Thank you!

**Comment by calh** [comment]
I think I might have solved this... the eth1 interface needs to have a LAN address assigned to it.  If I give it any valid address on the LAN, I can successfully run vrrpd with the shared IP address.

I believe the VRRP protocol needs that anyway, but I was hoping I could fire up a container without a dedicated address, and let the docker bridge handle the rest.  Does anyone know if there is a way to do that?

**Comment by fzansari** [comment]
Seems like you do not need pipework at all then. Please look at pipework documentation to see if it fits your usecase.

If you are running the docker containers on the same Host for High availability, you can simply use the native docker networking. 
When you start your docker it will come up with an ip address generally in the subnet 172.16.42.x/24. So all your containers on top of docker0 will be in this subnet. If this serves your purpose you do not need pipework.

eg. root@1404-1:~# docker run -i -t ubuntu
root@fe39d9e63a24:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:10:2a:03
          inet addr:172.16.42.3  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::42:acff:fe10:2a03/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:5 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:418 (418.0 B)  TX bytes:418 (418.0 B)

Please take a look at https://docs.docker.com/articles/networking/#container-networking

**Comment by calh** [comment]
I'm trying to do HA across different docker hosts. More specifically, these
are HAProxy containers. Is there a way to accomplish that with the native
docker daemon?

**Comment by fzansari** [comment]
The docker network is local to each docker Host(since the docker daemon is local). So on each host the same network(172.16.42.x) will be created. This will result in same ips on different hosts. That is not what you want.

I am not sure how you are connecting your hosts but basically you need some kind of docker multi host networking. This is not possible through the native docker networking. There are couple of options like weave,flanneld etc that you can use.

I have some scripts that use ovs to create a tunnel across multiple hosts. And then use some protocol like ping/arping etc. for ip management. Basically you need to ensure the ip addresses assigned to different dockers across the hosts do not share the same IP.

**Comment by calh** [comment]
Thanks for the info @fzansari, I have some pondering to do.  But for now, the original issue I reported was just my own fault, so I'm going to close this.
