### ISSUE TITLE
When using dhclient, default route is not added

### ISSUE THREAD

**Issue by Dmitriusan** [jpetazzo/pipework#144]
When using dhclient as dhcp client, I was not able to connect containers from another physical hosts (in different subnet). Server is properly configured for bridging and packet forwarding. Changing dhcp client to udhcpc immediately solved this issue for me. I assume that dhclient did not create default route for interface.
That should be stated in a doc, killed a lot of time wondering and checking my iptables config.

**Comment by jpetazzo** [comment]
Normally this should be solved by the new `dhcp` mechanism (which runs the DHCP client in a separate container). Thank you!
