### ISSUE TITLE
Access container via a local ip address

### ISSUE THREAD

**Issue by zainengineer** [jpetazzo/pipework#145]
Hi,

I am new to docker. How can I access container locally using static ip like `192.168.32.10` ?

Thanks.

**Comment by jpetazzo** [comment]
Hi,

I'd recommend to check [Docker networking documentation](https://docs.docker.com/articles/networking/). Then, if you have questions, you can ask for help on the [Docker User Mailing List](https://groups.google.com/forum/#!forum/docker-user) or on the #docker IRC channel on Freenode.

Thank you!
