### ISSUE TITLE
dhcp in vmware/virtualbox guests fails to hear DHCP server response

### ISSUE THREAD

**Issue by sdetweil** [jpetazzo/pipework#149]
I have an Ubuntu 14.04 physical host..  pipework works great to configure the network on containers using dhcpd (using udhcpc of course)..  I can start as many as I have resources for..

now to move this to my company network, where the systems I will use are actually virtual machines. 
the same scripts and containers time out getting the dhcp assigned address. 

the guest systems are setup in bridged mode, and get their ip addressed form the same DHCP server without issue. 

using dhcpdump on the host (primary interface etho and in the guest (eth0)
sees the dhcp request from the container as expected, and the dhcp offer response. 

except the container doesn't see the response. and times out. 

I 'suspect' that the bridged vmware/virtualbox  driver doesn't KNOW about the container mac address and so, doesn't listen for responses there.  

to test, I made a small container 
docker build -t foo .
Dockerfile
from ubuntu
cmd tail -f /var/log/bootstrap.log

the start the container with no networking

docker run -d --name=test --net=none --privileged  foo

docker exec test ip addr 
shows only the lo adapter..

bash -x pipework eth0 -i eth1 test dhcp

run on the host works great, 
now load up a vmware player image for Ubuntu 14.04

then use the same Dockerfile and steps..

no dhcp response., timeout, fails. 
docker exec test ip addr shows eth1 was created as expected. 

add dhcpdump -i eth0 to the host, and to the guest -i eth0

then run again. 

you will see the request (in both host and guest) and offer (only in host),  
docker exec test ip addr to get the mac address, and you will see that it matches
the request, and offer response packet data, but the guest doesn't see it. 

selinux is off, ufw disable to turn of any filters. 

edit: I don't need the host machine to talk to the docker containers over IP, so a bridge is not required. 

help.. trying to move my stuff to work environment.

**Comment by sdetweil** [comment]
Doah.. promiscuous mode.. right there in the doc..  not a network guy, so that word didn't mean anything to me..   does now!

working great on vmware and virtualbox.

**Comment by jpetazzo** [comment]
Cool, thanks for following-up!
