### ISSUE TITLE
/sbin/pipework: 274: kill: Illegal number: 

### ISSUE THREAD

**Issue by dreamcat4** [jpetazzo/pipework#150]
Not sure what is happening here...

First time pipework is called it returns an exit code 2. After waiting 5 seconds, the same pipework cmd is retry, and then it works.

https://gist.github.com/dreamcat4/34975af1714b6f916c3d

```sh
+ ip netns exec 29121 dhclient -pf /var/run/dhclient.29121.pid eth0
mv: cannot move '/etc/resolv.conf.dhclient-new.29301' to '/etc/resolv.conf': Device or resource busy
+ cat /var/run/dhclient.29121.pid
cat: /var/run/dhclient.29121.pid: No such file or directory
+ kill 
/sbin/pipework: 274: kill: Illegal number: 
++ '[' 2 '!=' 0 ']'
```

In shell, the commands were:

```sh
id@emachines-e520:~/docker-images$ docker start pipework ; sleep 15 ; docker start tvh
pipework
tvh
```

**Comment by dreamcat4** [comment]
Hmm. And then my wrapper script hangs / stops responding to further events.

My issue seems to have gone away either by moving from ubuntu `14.04` to `15.04`, or from `netcat` --> `curl`.

Perhaps there is nothing actionable here.

**Comment by dreamcat4** [comment]
This happens some times, but not other times. I also may get on the 2nd try:

```sh
+ ip netns exec 20832 dhclient -pf /var/run/dhclient.20832.pid eth0
RTNETLINK answers: Device or resource busy

```

Waiting 15 seconds until the retry has no effect.

**Comment by jpetazzo** [comment]
Do you think you could try with a different DHCP client?

I wonder if this might be caused by the fact that `dhclient` tries to clobber `/etc/resolv.conf`, which is actually a bind-mount (and has to be re-written instead of re-created).

**Comment by dreamcat4** [comment]
@jpetazzo Yeah sure! Although it was a long time ago I tried the others once. To my memory only 1 clients actually worked for me. Can't remember which one(s).

I'll try to re test it and then get back to you some better clues. Maybe I should also edit your script to `strace` the relevant command to see what it's doing on those runs vs the 'working times' (when the same cmd is run but there is not error).

This is good !

**Comment by dreamcat4** [comment]
@jpetazzo. Have now had the chance to get back to try this. Updated to latest pipework today with your new default busybox udhcpc client. From my limited testing (during 1 hour), it seems fantastic. Very happy. My docker image is updated to `v1.10` tag.

It seems to solve this issue entirely. I can't fault your analysis of the problem (trying to move the `resolv.conf`. Since there were other worse issues / hang with dhclient, there was little point going back to confirm it. As we can't do anything about it anyway.

**Comment by jpetazzo** [comment]
Thanks! Sorry that I couldn't check earlier. I have slated some time next week to go over open pipework issues, I hope I can crunch through the backlog :-)

**Comment by dreamcat4** [comment]
> I wonder if this might be caused by the fact that dhclient tries to clobber /etc/resolv.conf, which is actually a bind-mount (and has to be re-written instead of re-created).

It seems there will be some change in behaviour for docker v1.9.1

https://github.com/docker/docker/pull/14965

^^ Not sure if that helps dhclient does it? But at least dhclient would then be able to see the file is readonly... and maybe not be trying to move it / / update it / replace it.
