### ISSUE TITLE
VMWare Photon doesn't set DHCP provided IP address

### ISSUE THREAD

**Issue by sdetweil** [jpetazzo/pipework#151]
I am testing my docker/pipework process on different OS's.  Now testing under Virtualbox and VMWare. 

VMWare provides a new 'lightweight' host os..  it doesn't come with DHClient, so I downloaded and build isc-dhcp 4.3.2 (latest stable).  turned on adapter promiscuous mode, and see the dhcp client/server exchange

problem 1. the container interface is down (I added -v to the pipework invocation fo dhclient)

ip netns exec 519 dhclient -v -pf /var/run/dhclient.519.pid eth1
Internet Systems Consortium DHCP Client 4.3.2 
Copyright 2004-2015 Internet Systems Consortium. 
All rights reserved. 
For info, please visit https://www.isc.org/software/dhcp/ 
execve (/sbin/dhclient-script, ...): No such file or directory 
Listening on LPF/eth1/a2:ab: bd :27:14:d5 
Sending on   LPF/eth1/a2:ab: bd :27:14:d5 
Sending on   Socket/fallback 
DHCPREQUEST on eth1 to 255.255.255.255 port 67 
send_packet: Network is down 
dhclient.c:2248: Failed to send 300 byte long packet over eth1 interface. 
receive_packet failed on eth1: Network is down 

if I modify pipework again to set the container interface up, the dhcp process goes quickly, 
but doesn't stay set in the container

ip netns exec 683 ip link set eth1 up
ip netns exec 683 dhclient -v -pf /var/run/dhclient.683.pid eth1
Internet Systems Consortium DHCP Client 4.3.2
Copyright 2004-2015 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

execve (/sbin/dhclient-script, ...): No such file or directory
Listening on LPF/eth1/06:e3:86:35:ef:e0
Sending on   LPF/eth1/06:e3:86:35:ef:e0
Sending on   Socket/fallback
DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 4
DHCPREQUEST on eth1 to 255.255.255.255 port 67
DHCPOFFER from 192.168.2.1
DHCPACK from 192.168.2.1
execve (/sbin/dhclient-script, ...): No such file or directory
bound to 192.168.2.65 -- renewal in 3068 seconds.
  cat /var/run/dhclient.683.pid
  kill 730
  rm /var/run/dhclient.683.pid
  '[' dhclient = dhcpcd ']'
  installed arping
  command -v arping
  echo 'Warning: arping not found; interface may not be immediately reachable'
Warning: arping not found; interface may not be immediately reachable
  rm -f /var/run/netns/683

---- docker exec container ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
6: eth1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/ether 06:e3:86:35:ef:e0 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::4e3:86ff:fe35:efe0/64 scope link 
       valid_lft forever preferred_lft forever

is this a dhcp client problem?
the uname output of the Photon os
Linux photon 3.19.2 #1-photon SMP Wed Apr 15 22:37:11 UTC 2015 x86_64 GNU/Linux

**Comment by jpetazzo** [comment]
The DHCP process is supposed to exit once it's done. Would that explain the behavior you're seeing?

**Comment by sdetweil** [comment]
No. DHCP ends as expected, but the negotiated IP address is not set.

**Comment by sdetweil** [comment]
maybe what you are saying is that because DHClient ends, the ip address selected is removed.

with the latest pipework release, the ip address remains, but the busybox container used to get the address does not remain running like it does on ubuntu.

**Comment by jpetazzo** [comment]
OK, I think the initial problem came from the fact that the VMware lightweight host was missing a lot of important tools. We had similar issues with boot2docker, which is why I switched to the new DHCP method (running the DHCP client in a separate container).

If you have problems with the new methods, can you provide the logs of the DHCP container both on Ubuntu and on the VMware thing? 

Thank you!
