### ISSUE TITLE
dhcp: (dhclient) pipework hangs if container is restarted < 20 seconds

### ISSUE THREAD

**Issue by dreamcat4** [jpetazzo/pipework#152]
Hello!
Pipework hangs here:

```sh
+ ip netns exec 20832 dhclient -pf /var/run/dhclient.20832.pid eth0
RTNETLINK answers: Device or resource busy
[HANG]
```
For maybe ~10 minutes, perhaps longer?

That it is trying to make DHCP lease re-aquire (when it's dhclient) and the container is restarted < 20 seconds.

Log here: https://gist.github.com/dreamcat4/d05bfeadd06390ae68bb

The command run was like this:

```sh
$ docker stop tvh ; sleep 19 ; docker start tvh
```

And that causes the hang. What is interesting is that it occurs consistently for any wait time < 20 sec. If sleep = `20` exactly then is 'works' (first TCP connection afterward is broke, then 2nd TCP coneection its working). While if sleep = `22` then it does work reliably (even first TCP connection afterward).

I am guessing that this 20 second must be like a default timeout setting of my LAN DHCP server (or the local dhclient in this docker host system where pipework is run). Since the delay is exactly 20 secs.

Perhaps the DHCP server will refuse to honor a new least request until after the timeout has expired. (to stop it being grabbed prematurely). Anyway whatever the reason - the problem is that it is blocking for many minutes this command and the pipework script does not return or fail:

```sh
+ ip netns exec 20832 dhclient -pf /var/run/dhclient.20832.pid eth0
RTNETLINK answers: Device or resource busy
[HANG]
```

And that is the problem here. We would like the above command to actually return any error code immediately ^^ and not be hanging / waiting around for such long times. So if it exit promptly we can re-run again after a longer backing off the pipework script.

@jpetazzo Any input appreciated. This is running inside a `14.04` trusty container the dhclient version:

```sh
$ docker exec -it pipework dhclient --version
isc-dhclient-4.2.4
```

While outside on the host is `15.04` and newer dhclient (we not run it)

```sh
$ dhclient --version
isc-dhclient-4.3.1
```

I can upgrade my pipework container to newer dhclient and match the ubuntu version to `15.04` but I don't think it's the issue. Maybe an extra `dhclient` flags can help solve the hanging command (which not return) ? I will search around stack* sites.

If cannot find the problem, then might try to avoid with a default minimum timeout vaue of 22 seconds for all container restarts (at least, which are of DHCP).

**Comment by dreamcat4** [comment]
Happens on this line:

https://github.com/jpetazzo/pipework/blob/e51fd68ab461eaf575c0c037f5f8b871972ae413/pipework#L273

**Comment by dreamcat4** [comment]
@jpetazzo. Hi again. I'm closing this issue for same reasons as #274 - dhclient no good. Many thanks for the recent improvements to pipework dhcp functionality. Your new default busybox udhcpc client. From my limited testing (during 1 hour), it seems fantastic. Very happy. My docker image is updated to `v1.10` tag.

**Comment by jpetazzo** [comment]
Hi! Sorry for the lack of activity on this thread. I'm catching up on pipework activity (3 day week-end yay!!!) and indeed, I think the (only? easiest?) way to solve DHCP client discrepancies is with the "new" strategy implemented last month...

Thanks for your patience and for following up here!

**Comment by dreamcat4** [comment]
Yes. This issue is closed now because of the other solution you have already implemented.
