### ISSUE TITLE
port publish (port forwarding) doesn't work if added interface

### ISSUE THREAD

**Issue by santosh0705** [jpetazzo/pipework#154]
If you run your container with -p parameter and you add a new interface the forwarding stops working. It seems like there is issue with iptables, may have to add some rules but Im not verse in iptables.

example: I've an Apache image and I run it with -p 80:80 parameter and it publish the port 80 on host interface and I'm able to access the web server. As soon as a new interface is added it stop working.

Your help will be much appreciated.

**Comment by jpetazzo** [comment]
This is more-or-less expected, unfortunately!

If you *do* add a default route, it will replace the default route set by Docker, and it will break the default "flow" of traffic (and port forwarding). You will have to connect to the container using the new address set by pipework. The container will still be able to communicate with other local containers, though.

If you *do not* add a default route, then port mapping will continue to work like before.
