### ISSUE TITLE
pipework equivalent as events or plugin?

### ISSUE THREAD

**Issue by deitch** [jpetazzo/pipework#159]
Hey @jpetazzo 

Pipework is awesome. Really use it for clients to simplify amazing stuff.

Have you looked at or seen similar activities as events API driven or using 1.8+ plugins? I have had an issue that I cannot use pipework as part of an orchestration tool - they all use the Docker remote API, leaving little room to run a post-creation script like pipework. On the other hand, a plugin (1.8+) or events API (1.7-) could have the same effect....

Thinking about writing it if I cannot find it, but would prefer to find "pipework as a plugin" first.

**Comment by jpetazzo** [comment]
Unfortunately, I have approximately zero time to work on pipework :(

A plugin would be great but maybe we should wait for the interface to stabilize a bit.

**Comment by deitch** [comment]
Hmm, apparently I opened this in two different places. Sorry about that!

I will close this one, wait for your response to the suggested design on the other issue https://github.com/jpetazzo/pipework/issues/156

I agree about the interface. In the meantime, the events API is looking appealing...
