### ISSUE TITLE
pipework not work well on vmware

### ISSUE THREAD

**Issue by ChuangZhang** [jpetazzo/pipework#160]
my host is  running on the vmware  exsi hipervisor .   while,  when I use pipework config a local physical network to container it not working , there are my operate pictures result below:
![2222](https://cloud.githubusercontent.com/assets/5179187/8829514/94d390bc-30c9-11e5-82d0-1194bb498c51.png)
![111](https://cloud.githubusercontent.com/assets/5179187/8829517/9cc8d7f0-30c9-11e5-9980-218dff9c73fa.png)
the network is always Unreachable,  Is there anyone can help me ? thanks very much !

**Comment by jpetazzo** [comment]
Have you checked the VMware specific warning in the README?

**Comment by jpetazzo** [comment]
Closing older issues.
