### ISSUE TITLE
Can the pipework support a network bonding interface?

### ISSUE THREAD

**Issue by nskay** [jpetazzo/pipework#165]
Can the pipework support a network bonding interface?

I hope to use the pipework with a bonding interface like:
pipework bond0 -i eth0 testcontainer dhcp

But, it didn't work with no error message.
Is it possible that the pipework is used for a bonding interface?

Thanks!

**Comment by jpetazzo** [comment]
Hi!

Unfortunately, pipework does not support bonding interfaces directly.

If you want to "give" a bonded interface to a container, you have at least two strategies:

- "give" multiple interfaces to the container, then bond them from within the container;
- bond the interfaces outside the container, then transfer the bonded interface to the container.

Sorry!
