### ISSUE TITLE
Pipework fails with hostinterface eth0:3

### ISSUE THREAD

**Issue by Mellnik** [jpetazzo/pipework#167]
When connecting a local physical interface to a container named eth0:3 or eth0:2 ... pipework fails:

``I do not know how to setup interface eth0:3.``

The command looks as follows:

``pipework eth0:3 $(docker run -d --name somename -p 195.154.x.x:443:443 -p 195.154.57.x:x:80 mellnik/image) 195.154.x.x/24``

Using eth0 with another IP works. I am on CentOS 7.

**Comment by jpetazzo** [comment]
Yes, you can't use `eth0:x` because it's an IP alias. Just use `eth0` and it will behave exactly the same way!
