### ISSUE TITLE
Docker + plex + pipework , stuck with connection issues

### ISSUE THREAD

**Issue by spiroid** [jpetazzo/pipework#17]
Hi,

First, thanks a lot for your work on pipework, it is great :+1: 
I wasn't sure on how to contact you about an issue with pipework in my specific situation so i ended up describing it in this github issue.

I'm working on a docker + plex image [docker-plex](https://github.com/spiroid/docker-plex). All the work on pipework integration is commited on a pipework branch in the git repository.
As plex needs to access my local network i was trying to run my container with pipework to make an eth1 network interface with a private ip address in my local network.

However i didn't figure out how to make all pieces communicate.
1. First i started my container with `pipework --wait` to wait for eth1 to become available before launching plex.
2. Then i followed pipework readme file and on the host server i launched : 
   `sudo pipework wlan0 $CONTAINERID 192.168.111.16/24@192.168.111.254`.

It exit successfully and the eth1 interface was set up with the given ip address.
I also checked that the default gateway was correcly set which was the case.

However i couldn't make the container communicate with the outside world and with other computers on the private network. It wasn't reachable from other servers either. 
The only working network trafic was on the network set up by docker with the docker0 bridge (172.17.42.1 ip address on host).

Can you help me to make it all work ?
Did i miss something here ?

**Comment by jpetazzo** [comment]
Closing older issues.
