### ISSUE TITLE
how to set  network with container boot?

### ISSUE THREAD

**Issue by freelingchang** [jpetazzo/pipework#177]
example:
docker run -d   --name=object1  myobject /startup.sh
pipework  br0  object1  10.0.1.101/24@10.0.1.1
problem:
myobject  process connect  mysql(10.0.1.102)  with container boot.if set network after contarner boot,then myobject start failed,"connect mysql timeout".
how to  set network  with container boot ?

**Comment by dreamcat4** [comment]
Maybe you need to put the `pipework` script inside your container. Then use `pipework --wait -i eth0`.

https://github.com/jpetazzo/pipework#wait-for-the-network-to-be-ready
