### ISSUE TITLE
Does Pipework support IPv6, or is it on the roadmap?

### ISSUE THREAD

**Issue by timcoote** [jpetazzo/pipework#179]
A purely selfish request. I'm kicking off a project that's aimed at IoT and will seek to avoid NATting by using IPv6. I cannot find current IPv6 support, and I'd guess that there are ip address parsers and other ipv4 assumptions in the code.

Is there an intent to support IPv6 in some expected time period?

**Comment by combro2k** [comment]
docker exec ${CONTAINER} ip -6 addr add "${IP6ADDR}" dev "${DEV}" ? ;-)

**Comment by timcoote** [comment]
Good start :-)   However, there's a bit more to it than this, I think, as the routeing needs to work.  Typically,  docker containers would be hosted within a vm on some physical host. Ideally addresses would percolate through using RAs and SLAAC (clearly not how it works now). Unfortunately, the routes don't seem to get through either. For a set of containers on a vm, the link locals on docker0 of the vm respond to ND requests, but even the usual messing with accept_ra and forwarding do not seem to get the routeing through.

That problem sounds like the sort of infrastructure that pipework is aiming to help with. At least until Docker gets this area sorted.

**Comment by alexamirante** [comment]
I do use pipework to assign IPv6 addresses, with the usual sintex:
`./pipework <host_iface> -i <container_iface> <ipv6_address>/<netmask>@<gateway>`

**Comment by jpetazzo** [comment]
I don't have access to a nice IPV6 lab to do significant testing, unfortunately; but *in principle* at least, IPV6 support should "just work". If it doesn't, it might just be some tricky sysctl to set (which is easier said than done, of course...)

**Comment by combro2k** [comment]
i can have a look at it to get it working. got ipv6 support on my host. but will take some time
