### ISSUE TITLE
dhcpcd option seems to be broken

### ISSUE THREAD

**Issue by Dmitriusan** [jpetazzo/pipework#182]
Tried to use dhcpcd option, got error
Ubuntu 14.04, pipework revision 3bc5e90
```
bash pipework int-br system-jenkins dhcpcd 00:d0:33:22:11:22 
/sbin/dhcpcd-bin: invalid option -- 'q'
usage: dhcpcd [-adknpEGHMNRSTY] [-c script] [-h hostname] [-i classID]
              [-l leasetime] [-m metric] [-r ipaddress] [-s ipaddress]
              [-t timeout] [-u userclass] [-F none | ptr | both]
              [-I clientID] [-P pidfile] <interface>
```

**Comment by jpetazzo** [comment]
Right, it looks like `dhcpcd` doesn't support `-q`. I don't know what I was smoking when I wrote this! Want to submit a PR to change that? (It should be fairly simple)

**Comment by pppq** [comment]
Newer versions of `dhcpcd` interpret `-q` as "quiet", and no longer error out (it won't exit after retrieving an address, though). See http://roy.marples.name/man/html8/dhcpcd.html

**Comment by jpetazzo** [comment]
Since there are other DHCP options implemented, I'm going to close this issue. If someone absolutely needs to get *this* DHCP client to work, feel free to let me know so I can reopen!
