### ISSUE TITLE
Undo pipework config

### ISSUE THREAD

**Issue by AJNOURI** [jpetazzo/pipework#183]
After configuring:

> pipework br1 $CONTAINERID 192.168.4.25/20@192.168.4.1

Does pipework supports deleting a previously configured link from container to a bridge? 
Or at least change the default gateway back to eth0 (to host docker0)?

For that I have to stop the container and rerun it to remove pipework settings.

**Comment by jpetazzo** [comment]
I don't know if I understand.

Do you want to remove the `eth1` interface created by pipework? If that's the case, restoring the default gateway might indeed be tricky, alas.
