### ISSUE TITLE
Pipework doesn't wrok on  Ubuntu - ipcalc problem

### ISSUE THREAD

**Issue by nickmaleao** [jpetazzo/pipework#185]
Hello

I have been trying to run the last version of the pipework script in Ubuntu with no success.

Ubuntu:  
eval $(ipcalc -b 192.168.1.90/24)
sh: 1: eval: Address:: not found

Centos:
sh-4.1# eval $(ipcalc -b 192.168.1.90/24)
sh-4.1# echo $BROADCAST
192.168.1.255

After some tests, i noticed that the version of ipcalc in the Ubuntu repository is different that the one in redhat repos.

The -b option has different meanings in each ipcalc version 

Package version/details: 
Ubuntu: Version: 0.41-4 
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Bartosz Fenski <fenio@debian.org>

Centos: Version     : 0.41
AUTHORS
Erik Troan <ewt@redhat.com>
Preston Brown <pbrown@redhat.com>
IPv6 supported wedged in by David Cantrell <dcantrell@redhat.com>

______________________________________________________________________________

Options available for ipcalc in ubuntu:

-n --nocolor  Don't display ANSI color codes.
 -c --color    Display ANSI color codes (default).
 -b --nobinary Suppress the bitwise output.
 -c --class    Just print bit-count-mask of given address.
 -h --html     Display results as HTML (not finished in this version).
 -v --version  Print Version.
 -s --split n1 n2 n3             Split into networks of size n1, n2, n3.
 -r --range    Deaggregate address range.

Options available for ipcalc in centos:

 -c, --check         Validate IP address for specified address family
  -4, --ipv4          IPv4 address family (default)
  -6, --ipv6          IPv6 address family
  -b, --broadcast     Display calculated broadcast address
  -h, --hostname      Show hostname determined via DNS
  -m, --netmask       Display default netmask for IP (class A, B, or C)
  -n, --network       Display network address
  -p, --prefix        Display network prefix
  -s, --silent        Don't ever display error messages

I have uninstalled the ipcalc downloaded  from the ubuntu repos and compiled from source https://github.com/nmav/ipcalc, and now the pipework runs without any problem.

**Comment by jpetazzo** [comment]
I unfortunately don't have much time to maintain pipework, but if someone is running into this same issue, I'd suggest to replace the call to `ipcalc` by e.g. `docker run busybox ipcalc`. That will work great. I'm not putting that in mainline pipework since there might be users who don't have Docker though.
