### ISSUE TITLE
bridge to 'tap' interface in Docker container

### ISSUE THREAD

**Issue by jaychris** [jpetazzo/pipework#191]
I have an application (QEMU) running inside a docker container - it creates a tap interface (tap1) to allow for bridged networking.  Outside of Docker, you would just create a bridge (br0 or something) and add the tap interface to the bridge to talk to the qemu app.

Since I want to run it inside a Docker container (for a variety of reasons), _I'm wondering if/how I can use pipework to attach the 'tap' interface inside the container to a host bridge._  So that I can communicate to my QEMU application inside the container from the host, through the bridge.

I was able to get a real frankenstein working, where I created a bridge _inside_ the container (br0), added the tap interface to that, and then used pipework to create a new host bridge and an "eth1" interface inside the container, and then added the new container interface "eth1" to the the container bridge "br0".  I said it was frankenstein, right?

But that's all very clutter-y and it seems like there should be a better, cleaner way to do it with pipework, but I'm just not seeing it.

**Comment by jpetazzo** [comment]
Your solution is not bad, in the sense that it allows to compose multiple simple things to achieve a complex thing. From the host perspective, there is just an extra veth, going to the container; and inside the container, there is that extra bridge.

If you want to avoid the extra bridge, you can move the tap interface *from the container to the host* but pipework was not designed to do that at all... You could borrow pieces from it, though.

**Comment by ankitgupta29** [comment]
@jaychris  Hi, i am also trying to figure out how to get my tap interfaces inside container to expose it to the host machine or should be able to direct traffic from host to tap interface inside the container? Did you get any luck on doing that? Thank you for your time.

**Comment by jaychris** [comment]
@ankitgupta29, I got it to work the way I described in my original post, where I created a bridge inside the container, added the tap interface, and then used pipework to create a new host bridge, etc., etc...  

The reason I opened this issue was to see if there might have been a simpler way to accomplish the same thing.  I started down the road that jpetazzo suggested, but in the end, we ended up abandoning the project and I never went back to it.  So, the solution I originally described is where we ended up.

**Comment by ankitgupta29** [comment]
@jaychris  Thank you for reply. I am new to docker networking and need little help to understand.

I have created the following configuration:
Docker host:
1. created a docker container.
2. created a bridge network br1, this creates a eth1 network interface inside docker and another veth interface on the host.

Docker Container:
1. Ran my application, that create a tap_interface with ip assigned: 192.168.36.9
2. created a bridge network br0, attached eth1 and tap_interface to it.

Now my question is how to ping tap_interface from host directly.
from Host:
ping 192.168.36.9

-------here is my snapshot of config of my host and container----------

**========================================
Host Configuration
========================================**

root@ctuser-virtual-machine:/home/ctuser# 

root@ctuser-virtual-machine:/home/ctuser# ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:6e:14:aa:29  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:6eff:fe14:aa29/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1486052 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1083981 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:257380802 (257.3 MB)  TX bytes:295402059 (295.4 MB)

ens160    Link encap:Ethernet  HWaddr 00:50:56:a8:6a:d4  

          inet addr:10.0.102.106  Bcast:10.0.103.255  Mask:255.255.254.0
          inet6 addr: fe80::f27b:154e:f885:3cd8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:16934798 errors:30 dropped:30 overruns:0 frame:0
          TX packets:16659774 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1723875694 (1.7 GB)  TX bytes:5816610754 (5.8 GB)

veth0c4559a Link encap:Ethernet  HWaddr c2:1b:52:be:26:31  
          inet6 addr: fe80::c01b:52ff:febe:2631/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:50834 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11372717 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:9024202 (9.0 MB)  TX bytes:2956735550 (2.9 GB)

**root@ctuser-virtual-machine:/home/ctuser# 
root@ctuser-virtual-machine:/home/ctuser# brctl show br1
bridge name	bridge id	STP enabled	interfaces
br1	8000.ce1170490f49	no	veth1pl13076**

**=====================================================================
Docker Configuration
=======================================================================**

root@ctuser-virtual-machine:/home/ctuser# docker ps

CONTAINER ID        IMAGE                      COMMAND             CREATED             STATUS              PORTS               NAMES
f3a4bb186d65        ct-lgm-test-image-latest   "/sbin/init"        10 hours ago        Up 10 hours         22/tcp              kind_torvalds

root@ctuser-virtual-machine:/home/ctuser# docker exec -it f3a4bb186d65 /bin/bash
root@f3a4bb186d65:/# 

**root@f3a4bb186d65:/# brctl show br0
bridge name	bridge id	STP enabled	interfaces
br0	8000.5efd1d57846e	no	ctm-cf8e67d956e
                                                        eth1**

root@f3a4bb186d65:/# ifconfig
tap_interface Link encap:Ethernet  HWaddr 5e:fd:1d:57:84:6e  
          inet addr:192.168.36.9  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:9000  Metric:1
          RX packets:3159 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3180 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:2000 
          RX bytes:181162 (181.1 KB)  TX bytes:160353 (10.3 KB)

eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:02  
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:11372708 errors:0 dropped:0 overruns:0 frame:0
          TX packets:50823 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2956733660 (2.9 GB)  TX bytes:9022200 (9.0 MB)

eth1      Link encap:Ethernet  HWaddr 8e:20:86:da:2e:06  
          inet addr:10.40.33.21  Bcast:0.0.0.0  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:35 errors:0 dropped:0 overruns:0 frame:0
          TX packets:13 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3962 (3.9 KB)  TX bytes:546 (546.0 B)

**Comment by jpetazzo** [comment]
Hi!

Thank you for your interest. ❤️ 

I wish I could help you further, but alas, I have stopped working on pipework, and I don't see an obvious answer to your question. 🤔

If you're still actively looking for an answer, I'd suggest that you check or ask through:
- the [Docker Community Forums](http://forums.docker.com/)
- the Docker tag on [StackOverflow](https://stackoverflow.com/questions/tagged/docker)
- the [Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)

If this is a critical issue for you, I know a few amazing consultants that you might want to hire. Let me know how to contact you and I'll put you in touch with them.

Thank you!
