### ISSUE TITLE
Unable to run paperwork after clone

### ISSUE THREAD

**Issue by sandeepthota** [jpetazzo/pipework#193]
I have cloned using command 
I am not able to use the pipework script as after I clone
"git clone https://github.com/jpetazzo/pipework.git" and try to run
pipework ovsbr0 -i eth0 $(docker run --net='none' busybox /bin/sh) dhcp

It says "pipework: command not found"

**Comment by jpetazzo** [comment]
Try `./pipework` instead?

**Comment by stanpcf** [comment]
I have same problem on ubuntu 16.04. 
after try I find that that file 'pipework/pipework' have no permission to execute , run cmd "ls -a pipework/pipework",  show pipework file's info "-rw-r--r--". so we need to 'chmod +x pipework/pipework'. It work fine on my ubuntu os :-)
