### ISSUE TITLE
Is there any way to prevent docker containers from changing IP address after every restart?

### ISSUE THREAD

**Issue by Saravana9210** [jpetazzo/pipework#194]
I'm new to docker world. I am wondering is there any way to prevent docker containers from changing IP address after every restart?

I read about pipework, but somehow I'm not clear about it. Can anyone suggest anyother solution. Or, please redirect me to correct place where I can understand **Pipework** better.

Thanks in advance :)

**Comment by jpetazzo** [comment]
You can use `docker run --ip <ip address>` but this is definitely not recommended. When possible, you should try to find another way (than forcing the IP address)>. For more details, I invite you to explain your full use case on the [Docker User mailing list](https://groups.google.com/forum/#!forum/docker-user). Thank you!
