### ISSUE TITLE
pipework dhclient option does not work

### ISSUE THREAD

**Issue by sainath14** [jpetazzo/pipework#196]
I launched ubuntu docker container with
docker run -it --net=none ubuntu bash

docker assigned name is berserk_bassi

then i wanted to create an interface inside the container with dhcp ip

I did the following
./pipework br1 berserk_bassi dhclient

The script returns but the container gets an eth1:avahi interface as the dhcp fails to get an IP for the interface.
Is something missing with regards to programming the bridge and iptables on the host side?

**Comment by enterit** [comment]
I have the same question. Does it work for Docker version 1.10.3?

**Comment by jpetazzo** [comment]
If somebody has a similar problem – please open a new issue, indicating your host distro and Docker version. (And be patient – I'm not actively maintaining pipework! :-))
