### ISSUE TITLE
Assign Network Interface to Container

### ISSUE THREAD

**Issue by bubba-h57** [jpetazzo/pipework#197]
We have an issue with network bandwidth being the bottleneck for our containers on an AWS EC2 instance. I'd like to simply add additional Network Interfaces to the instance, and then have no more than two containers share a single Network Interface ... or possible give each container it's own interface in order to minimize the contention.

Is that even possible? Could you point me toward an example of how it would be done?

**Comment by mmonaco** [comment]
It's possible in Linux to assign physical interfaces to a network namespace. But pipework doesn't currently work like that, instead it creates a macvlan and assigns that to the container's network namespace. If you want containers to share a physical interface, you either need to use macvlans or you need one container to run in the namespace of another (a feature supported by docker run --net). I'd be surprised if going through this trouble buys you much more bandwidth.

**Comment by jpetazzo** [comment]
I would advise to use `--net host` for these containers; that's the easiest solution.

(Of course if you have multiple containers and multiple interfaces you will need to make sure that each container binds to the correct interface; but it might be easier than poking around with pipework :-))
