### ISSUE TITLE
pipework eth0 container_id dhclient fails

### ISSUE THREAD

**Issue by mariusnita** [jpetazzo/pipework#199]
```
$ sudo pipework usb0 -i eth1 test_sshd dhclient
/usr/local/bin/pipework: 205: /usr/local/bin/pipework: Bad substitution
```

This is on ubuntu 14.04. I think the syntax `${foo: -2}` doesn't work on ubuntu /bin/sh (dash).

```
$ /bin/sh
$ x="123"
$ echo ${x: -2}
/bin/sh: 2: Bad substitution
```

**Comment by jpetazzo** [comment]
I wasn't able to reproduce the issue on a fresh Ubuntu 14.04 instance. Feel free to reopen if you still see the problem with the latest version of pipework!
