### ISSUE TITLE
want to add an infiniband interface to container, but get RTNETLINK answers: Operation not supported

### ISSUE THREAD

**Issue by dabianzhixing** [jpetazzo/pipework#200]
I 'm trying to add an infiniband interface to container using the command 
    pipework ib0 test1 10.0.1.3/24
but the error is "RTNETLINK answers: Operation not supported", I use the "sh -x  pipework ib0 test1 10.0.1.3/24" to rerun the command. following is the output:
- set -e
- IFNAME=ib0
- CONTAINER_IFNAME=
- [ test = -i ]
- [ test = -l ]
- GUESTNAME=test
- IPADDR=10.0.1.3/24
- MACADDR=
- VLAN=
- [ 10.0.1.3/24 ]
- [ -z  ]
- [ -d /sys/class/net/ib0 ]
- [ -d /sys/class/net/ib0/bridge ]
- installed ovs-vsctl
- command -v ovs-vsctl
- cat /sys/class/net/ib0/type
- [ 32 -eq 32 ]
- IFTYPE=ipoib
- CONTAINER_IFNAME=ib0
- PKEY=
- CONTAINER_IFNAME=ib0
- [  ]
- [ ipoib = bridge ]
- [ ipoib = ipoib ]
- [  ]
- read _ mnt fstype options _
- [ sysfs != cgroup ]
- continue
- read _ mnt fstype options _
- [ proc != cgroup ]
- continue
- read _ mnt fstype options _
- [ devtmpfs != cgroup ]
- continue
- read _ mnt fstype options _
- [ devpts != cgroup ]
- continue
- read _ mnt fstype options _
- [ tmpfs != cgroup ]
- continue
- read _ mnt fstype options _
- [ ext4 != cgroup ]
- continue
- read _ mnt fstype options _
- [ tmpfs != cgroup ]
- continue
- read _ mnt fstype options _
- [ fusectl != cgroup ]
- continue
- read _ mnt fstype options _
- [ debugfs != cgroup ]
- continue
- read _ mnt fstype options _
- [ securityfs != cgroup ]
- continue
- read _ mnt fstype options _
- [ tmpfs != cgroup ]
- continue
- read _ mnt fstype options _
- [ tmpfs != cgroup ]
- continue
- read _ mnt fstype options _
- [ tmpfs != cgroup ]
- continue
- read _ mnt fstype options _
- [ cgroup != cgroup ]
- echo rw,relatime,cpuset
- grep -qw devices
- continue
- read _ mnt fstype options _
- [ pstore != cgroup ]
- continue
- read _ mnt fstype options _
- [ cgroup != cgroup ]
- echo rw,relatime,cpu
- grep -qw devices
- continue
- read _ mnt fstype options _
- [ cgroup != cgroup ]
- echo rw,relatime,cpuacct
- grep -qw devices
- continue
- read _ mnt fstype options _
- [ cgroup != cgroup ]
- echo rw,relatime,memory
- grep -qw devices
- continue
- read _ mnt fstype options _
- [ cgroup != cgroup ]
- echo rw,relatime,devices
- grep -qw devices
- CGROUPMNT=/sys/fs/cgroup/devices
- read _ mnt fstype options _
- [ cgroup != cgroup ]
- echo rw,relatime,freezer
- grep -qw devices
- continue
- read _ mnt fstype options _
- [ cgroup != cgroup ]
- echo rw,relatime,net_cls
- grep -qw devices
- continue
- read _ mnt fstype options _
- [ cgroup != cgroup ]
- echo rw,relatime,blkio
- grep -qw devices
- continue
- read _ mnt fstype options _
- [ cgroup != cgroup ]
- echo+  rw,relatime,perf_event
  grep -qw devices
- continue
- read _ mnt fstype options _
- [ cgroup != cgroup ]
- echo rw,relatime,net_prio
- grep -qw devices
- continue
- read _ mnt fstype options _
- [ cgroup != cgroup ]
- echo rw,relatime,hugetlb
- grep -qw devices
- continue
- read _ mnt fstype options _
- [ cgroup != cgroup ]
- echo rw,nosuid,nodev,noexec,relatime,name=systemd
- grep -qw devices
- continue
- read _ mnt fstype options _
- [ rpc_pipefs != cgroup ]
- continue
- read _ mnt fstype options _
- [ fuse.gvfsd-fuse != cgroup ]
- continue
- read _ mnt fstype options _
- [ ext4 != cgroup ]
- continue
- read _ mnt fstype options _
- [ nsfs != cgroup ]
- continue
- read _ mnt fstype options _
- [ aufs != cgroup ]
- continue
- read _ mnt fstype options _
- [ tmpfs != cgroup ]
- continue
- read _ mnt fstype options _
- [ nfs4 != cgroup ]
- continue
- read _ mnt fstype options _
- [ aufs != cgroup ]
- continue
- read _ mnt fstype options _
- [ tmpfs != cgroup ]
- continue
- read _ mnt fstype options _
- [ nsfs != cgroup ]
- continue
- read _ mnt fstype options _
- [ /sys/fs/cgroup/devices ]
- find /sys/fs/cgroup/devices -name test
- wc -l
- N=0
- installed docker
- command -v docker
- RETRIES=3
- [ 3 -gt 0 ]
- docker inspect --format={{ .State.Pid }} test
- DOCKERPID=10289
- [ 10289 != 0 ]
- break
- [ 10289 = 0 ]
- [ 10289 = <no value> ]
- [ ipoib != route ]
- :
- [  ]
- [ 10289 ]
- NSPID=10289
- [ ipoib = phys ]
- [ ! -d /var/run/netns ]
- rm -f /var/run/netns/10289
- ln -s /proc/10289/ns/net /var/run/netns/10289
- [ ipoib = bridge ]
- [ ipoib != route ]
- [ ipoib != dummy ]
- ip link show ib0
- awk {print $5}
- MTU=2044
- [ ipoib = bridge ]
- [ ipoib = phys ]
- [ ipoib = ipoib ]
- GUEST_IFNAME=ib0.10289
- [  ]
- ip link add link ib0 name ib0.10289 type ipoib
  RTNETLINK answers: Operation not supported

I don't know what happen, what should i do?

**Comment by jpetazzo** [comment]
I would suggest to manually try to create an IP-over-IB interface to make sure that this works correctly.
