### ISSUE TITLE
setting container internal interface error when use centos7.2

### ISSUE THREAD

**Issue by guotaoli429** [jpetazzo/pipework#202]
I use CentOS-7-x86_64-Minimal-1511.iso create a vm,where i use pipework setting container internal interface,the internal interface isn't setted correct.
The command like below:
./pipework br0 -i eth0 -l test test 10.110.18.217/24@10.110.18.254
The result like below:
eth0@if24: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
I counfuse why the internal interface is appended with @if24 suffix.

**Comment by jpetazzo** [comment]
Hi,

I'm sorry, I can't really offer support for pipework through GitHub issues!
