### ISSUE TITLE
arping hangs for dhcp?

### ISSUE THREAD

**Issue by kladkogex** [jpetazzo/pipework#210]
if installed arping; then
    IPADDR=$(echo "$IPADDR" | cut -d/ -f1)
    ip netns exec "$NSPID" arping -c 1 -A -I "$CONTAINER_IFNAME" "$IPADDR" > /dev/null 2>&1 || true

Is this correct code in case $IPADDR=dhcp?

arping seems to hang in this case

**Comment by jpetazzo** [comment]
`arping` should send only one packet, and this is a gratuitous ARP packet so it shouldn't wait for a reply.

If you still see the problem, please re-open the issue and report the exact distro that you are using on the host!

Thank you.
