### ISSUE TITLE
running command on nas system synology dsm error

### ISSUE THREAD

**Issue by sentball** [jpetazzo/pipework#224]
the main error is grep -w not support, use command grep --help to know

seem the code line is 
`echo "$options" | grep -qw devices || continue`

**Comment by sentball** [comment]
i am running docker on synology dsm

**Comment by jpetazzo** [comment]
I don't think pipework can function without GNU tools, sorry!

(i.e. the `grep` on the synology seems to be a lightweight version, missing options needed by pipework.)

Sorry again!
