### ISSUE TITLE
after a container termination its interface is not destroyed

### ISSUE THREAD

**Issue by FarzanehPir** [jpetazzo/pipework#233]
Thank you for creating pipework. It's very cool and very easy to use. 
However, I have a problem with it recently and I hope I can find a solution for it.
After upgrading the kernel version of my ubuntu server to 5.0.0-20, I added an IP with the following command to my container:  
pipework br0 -i eth1 CONTAINER 192.168.1.25/29@192.168.1.1

It worked fine but when I stopped the container, its network was not destroyed completely. I can ping the IP . I tried to find the interface on the host or on the container and remove it manually  but I could not find anything. After restarting the server the ping was gone and the problem was solved.
Is there a way to remove the IP‌ manually from the container (without container termination)? or do you have any idea for solving the issue?

**Comment by jpetazzo** [comment]
Closing old issues.
