### ISSUE TITLE
Macvlan DHCP fails with 'Error: argument "1500' with both dhclient and dhcp

### ISSUE THREAD

**Issue by sotiris-bos** [jpetazzo/pipework#234]
Command: `./pipework eno1 ef4af12907f5 dhclient`

Output:
```
Error: argument "1500

spoof
spoof
spoof
spoof" is wrong: Invalid "mtu" value

```

No interface gets added to the container. Same thing with `dhcp` instead of `dhclient`.

Centos 8, 4.18.0-80.11.2.el8_0.x86_64
Docker version 19.03.5, build 633a0ea

**Comment by jpetazzo** [comment]
Hi!

Sorry, I don't maintain pipework anymore. If you want to obtain an address over DHCP, I'd suggest to run the DHCP client in a container (for instance, started with `docker run --net container:...`) for consistency.
