### ISSUE TITLE
Not passing dhclient options correctly: "hostnametest" is invalid lladdr

### ISSUE THREAD

**Issue by sotiris-bos** [jpetazzo/pipework#235]
I am trying to pass the `-H hostnametest` parameter to `dhclient` with `dhclient:-H hostnametest` but I am getting a `"hostnametest" is invalid lladdr` error.

Any ideas?

Edit: Options need to be encased in doublequotes: `dhclient:"-H hostnametest"` .
Documentation should be updated to reflect this.

**Comment by Candy1117** [comment]
pipework br0 nginx1 10.0.114.222/24@10.0.114.1
head: cannot open ‘/tasks’ for reading: No such file or directory

**Comment by jpetazzo** [comment]
Closing old issues.
