### ISSUE TITLE
Solving RTNETLINK error

### ISSUE THREAD

**Issue by djatnieks** [jpetazzo/pipework#24]
I'm getting this error trying to run pipework - it's not a pipework problem AFAICT, but do you have any ideas? An old Centos kernel or I need a different version of iptables or something? TIA!

(grave_brattain is my container name):
sudo ./repos/pipework/pipework br1 grave_brattain 172.17.6.100/24
RTNETLINK answers: Operation not supported

$ uname -a
Linux blade-1-4a.dssunnyvale.lan 2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

iptables --version
iptables v1.4.7

$ sudo docker version
Client version: 0.7.2
Go version (client): go1.1.2
Git commit (client): 28b162e/0.7.2
Server version: 0.7.2
Git commit (server): 28b162e/0.7.2
Go version (server): go1.1.2
Last stable version: 0.7.6, please update docker

**Comment by jpetazzo** [comment]
Closing older issues.
