### ISSUE TITLE
Could this project be compatible with Podman containers?

### ISSUE THREAD

**Issue by q2dg** [jpetazzo/pipework#241]
Thanks!

**Comment by jpetazzo** [comment]
Hi!

It may, or it may not. I have zero experience with podman. I suppose that it's also using Linux kernel namespaces for networking. If that's the case, pipework will be compatible. You would need to patch it to resolve a podman container ID/name (if it has these concepts) to a process ID.

**Comment by q2dg** [comment]
Yes, it does.
Maybe this article is helpful: https://www.redhat.com/sysadmin/container-networking-podman (and in a lot less detail, https://podman.io/getting-started/network.html)
Thanks!
