### ISSUE TITLE
vethxxx cannot be added into bridge 

### ISSUE THREAD

**Issue by Lipeilin0624** [jpetazzo/pipework#247]
Hi, 
       Now we have a problem,  the vethxxx of docker can not be added into bridge.  I am wondering if you've ever encountered similar problems. can you look into it and give me a feedback? Any suggestions would be highly appreciated. Thank you. 

![image](https://user-images.githubusercontent.com/97716846/149447251-289e88b5-b198-49cf-92ab-0214c7d9a62f.png)

And, i see the code of pipework is that the command of "ip link set "$LOCAL_IFNAME" master "$IFNAME" " is before the command of "ip link set "$LOCAL_IFNAME" up", but  i see the rule is To add an interface (e.g. eth0) into the bridge, its state must be up, I would really appreciate if you can help me.  

![image](https://user-images.githubusercontent.com/97716846/149457043-76d2d48a-1b8a-4524-8960-4b4aae601f3b.png)

**Comment by jpetazzo** [comment]
Closing old issues.
