### ISSUE TITLE
 I want to hire an expert for a project

### ISSUE THREAD

**Issue by leoborlot** [jpetazzo/pipework#251]
Hi guys, I need to hire soe one to help me in one project using this pipework projetce. This is the jobs. 

- I have a serve with 16 ips, these ips was set Vlan like:  eth0-1, eht0-2, eth0-3.
- I nedde to run 16 container, but each container nees to set to send outgoing requests from specific IP. 
- At the end os job, each container will send request for out, using an a difent IP, on for each 16 ips from server.

Any on want to catch this job?

**Comment by jpetazzo** [comment]
I hope you were able to either figure it out, or find someone to help. I'm cleaning up old issues here, so I'm going to close this. Thank you!
