### ISSUE TITLE
support for fedora

### ISSUE THREAD

**Issue by xdays** [jpetazzo/pipework#44]
I use fedora, there's no package related to udhcpc，I changed to dhclient。 but it seemed this tools does not work with fedora

<pre>
/usr/local/sbin/pipework: line 177: 13867 Segmentation fault      ip link add link $IFNAME dev $GUEST_IFNAME type macvlan mode bridge
</pre>

**Comment by dubglan** [comment]
@xdays 
We hit this issue sometimes (about once in 100k container provisionings). This appears to be a kernel problem, still researching which one. In our case we're using 0/0 IP and then run dhclient from within Docker container. You can take a look at https://bugzilla.redhat.com/show_bug.cgi?id=1091779
