### ISSUE TITLE
Why not delete task id from /var/run/netns after script done?

### ISSUE THREAD

**Issue by PeerXu** [jpetazzo/pipework#52]
If we leave the task id on /var/run/netns, it may be found on iproute2 tool (ip netns).
But docker should not found by ip netns.
So, cloud we delete task id when the script done?

**Comment by psi-4ward** [comment]
Could you please epxlain to me why we delete the netns?

**Comment by PeerXu** [comment]
because we cloud not show docker on `ip netns` :)
