### ISSUE TITLE
[Q] How does the creation of a veth pair for docker work

### ISSUE THREAD

**Issue by tlindener** [jpetazzo/pipework#55]
Hi,

thank your very much for this great script. I'm working on something quite similar but only focused on docker and openvswitch. For this scenario I need to create a variable number of veth pairs for a container. 
Would you be so kind to explain how the script gathers the relevant data from a docker container to create the veth pair. From what I understand it's basically these 3 lines that create the pair:
    LOCAL_IFNAME=pl$NSPID$CONTAINER_IFNAME
    GUEST_IFNAME=pg$NSPID$CONTAINER_IFNAME
    ip link add name $LOCAL_IFNAME type veth peer name $GUEST_IFNAME

I would be really thankful!

[edit]:
On a related matter: do you know whether it is possible to add a veth link directly between two container?

**Comment by OwenChang** [comment]
I have a question, what is the symbolic link effect in creating the veth pair？

> ln -s /proc/$NSPID/ns/net /var/run/netns/$NSPID

**Comment by jpetazzo** [comment]
The symlink is there, because when you use `ip` with the `netns` options, when you refer to a network namespace named `foo`, it will look for a file in `/var/run/netns/foo` which should point to the `net` pseudo-file in the namespace directory.
