### ISSUE TITLE
Name too long with -i option

### ISSUE THREAD

**Issue by ashahab-altiscale** [jpetazzo/pipework#58]
If we provide a -i option(container interface) thats longer than 8 characters, pipework throws the following error: Error: argument "peer" is wrong: "name" too long

This is because the name is longer than 15 characters, and ip link add name does not allow that.

Can we have another option that allows the caller to provide the entire interfacename, and so the caller has greater flexibility in naming the interfaces?

**Comment by jpetazzo** [comment]
Closing older issues.
