### ISSUE TITLE
Generate README toc with "doctoc"?

### ISSUE THREAD

**Issue by jpetazzo** [jpetazzo/pipework#70]
I was told: `npm install doctoc`. I'll have to test it some day.

**Comment by dreamcat4** [comment]
@porjo AFAICT mediawiki format is not supported / scanned by Dockerhub. Only a `README.md` in markdown format will be used.

@jpetazzo `npm install -g doctoc && cd pipework && doctoc`. Is definitely the least hassle way to generate TOCs for github `README.md`s at the moment. So long as you can be bothered to install `node.js` first.

**Comment by jpetazzo** [comment]
Thank you @dreamcat4! This turned out to be way easier than I thought :-)
