### ISSUE TITLE
Help configuring Docker Containers with DHCP addresses.

### ISSUE THREAD

**Issue by djl197** [jpetazzo/pipework#71]
I have a server (Ubuntu 12:04.4) with a single static IP address on my corporate network:
eth0 - a.b.c.d

I want to run multiple docker containers on this machine - I would like each of them to be assigned a DHCP address from the corporate DHCP server.

I am rather confused about how to go about this...
I thought I could start the container and then using pipework do the following
pipework eth0 <CONTAINER_ID> dhcp

However this gives me:
mkdir: cannot create directory `/var/run/netns': Permission denied

I started to look around at other options:
Should I replace eth0 on my server(host) with a Bridged Ethernet setup:
http://www.havetheknowhow.com/Configure-the-server/Network-Bridge.html

I could then tell docker to use a pre-created bridge and then try pipework.

I also looked at using lxc-conf:
docker run -i -t -lxc-conf='lxc.network.type=veth' -lxc-conf='lxc.network.link=eth0' -lxc-conf='lxc.network.name=eth0' -lxc-conf='lxc.network.ipv4=0.0.0.0' -lxc-conf='lxc.network.flags=up' <IMAGE> <CMD>

But that did not appear to work either.
Any help or advice much appreciated.

Dan

**Comment by jpetazzo** [comment]
This is hopefully solved by the latest version of pipework which uses the busybox DHCP client :-)
