### ISSUE TITLE
dhclient on ubuntu 14.04 not have -H param 

### ISSUE THREAD

**Issue by better0332** [jpetazzo/pipework#76]
[ $DHCP_CLIENT = "dhclient"  ] && ip netns exec $NSPID $DHCP_CLIENT $CONTAINER_IFNAME -H $GUESTNAME

**Comment by jpetazzo** [comment]
With the code that now detects the DHCP client, this should not be a problem anymore. Closing.

**Comment by envygeeks** [comment]
This is still a problem @jpetazzo because those of us that ask that pipework explicitly use our dhclient end up with a broken implementation that sends -H on Debian what intrigues me though is how autodetection will fix that:

```
+ GUEST_IFNAME=ph12002eth1
+ ip link add link eth0 dev ph12002eth1 mtu 1500 type macvlan mode bridge
+ ip link set eth0 up
+ ip link set ph12002eth1 netns 12002
+ ip netns exec 12002 ip link set ph12002eth1 name eth1
+ [  ]
+ ip netns exec 12002 dhclient eth1 -pf /var/run/dhclient.12002.pid -H minidlna
```

**Comment by jpetazzo** [comment]
Hmm, the new code will use the busybox client in a separate container. If you want to force it to use the "local" dhclient, then please describe to me how it should be changed -- I mean, what is wrong with current syntax, and what correct syntax would look like; and I'll be happy to look at the changes!

Thank you!

**Comment by envygeeks** [comment]
@jpetazzo The current syntax uses `-H` on dhclient, don't use `-H` because it's not portable, that's what the original ticket asked for and that's what I'm asking for.  Simply remove the `-H` on dhclient.  It's smart enough to infer the hostname itself not to mention being able to customize the hostname on Docker anyways so there is no need to try and force a hostname.

**Comment by jpetazzo** [comment]
Thanks for being patient and explaining the issue to me; I had totally overlooked it. I understand now! I hope 638e035 will be satisfactory for everyone.

**Comment by envygeeks** [comment]
Thanks @jpetazzo!
