### ISSUE TITLE
Help with configuring DHCP on pipework

### ISSUE THREAD

**Issue by loneshaman** [jpetazzo/pipework#85]
Hi all,

I'm currently running docker 1.2 on CentOS 7, and have been trying (unsuccessfully) to assign an IP address to a container using DHCP and pipework.

The command i use to start the container is:

docker run --privileged=true -i -t -d --name <container_name> centos /bin/bash

The pipework command is:

pipework eth0 <container_name> dhcp

As soon as I enter this command, I get the response "I do not know how to setup interface eth0".

What am I doing wrong? I'm extremely new to docker, pipework, and network stuff in general, so please forgive my lack of knowledge.

**Comment by jpetazzo** [comment]
Closing older issues.
