### ISSUE TITLE
Integrate pipework in to the docker

### ISSUE THREAD

**Issue by nadrimajstor** [jpetazzo/pipework#88]
:+1:

**Comment by dreamcat4** [comment]
FYI:

With docker 1.5.0, I have been able to put pipework into a container. So that it can run alongside your other containers. You can find it on docker hub as the `dreamcat4/pipework` docker image. Or just search for "pipework" on docker hub.

**Comment by nadrimajstor** [comment]
@dreamcat4 Have I got this right: Its a privileged container that sets up network for other containers?

**Comment by dreamcat4** [comment]
@nadrimajstor Yes. That is 100% correct.
