### ISSUE TITLE
help setting Docker DHCP+DNS for my network

### ISSUE THREAD

**Issue by ehudkaldor** [jpetazzo/pipework#94]
I keep finding partial answers to this, so maybe someone here will know:
I am trying to set up a home network, with Ubuntu running Docker, with a container running DNSMASQ (or ISC DHCP + BIND9) to serve the network. the Docker host (Ubuntu) will be wired to the cable modem, and to a wireless access point.
so, 
* the DNSMASQ container needs to be able to serve the real network
* preferably, the Ubuntu host will get its IP from DNSMASQ after it boots and starts teh container, but i can live with having a static IP on it.
* DNSMASQ needs to be able to route outside.
* another container will run IPtables and will serve as the gateway. its gateway will be the modem.
wow, that sounds like a lot now that i type it. any other approach to getting this done is welcome too. i already thought of running a VM on libvirt to serve the same purpose.

bonus: have multiple networks based on VLANs,  each with its own DHCP container.

wow.

**Comment by ehudkaldor** [comment]
bump?

**Comment by jpetazzo** [comment]
Would this help you:

https://github.com/jpetazzo/pxe

It shows how to run a PXE server (and therefore, a DHCP server) in a container.

**Comment by jpetazzo** [comment]
Closing older issues.
