### ISSUE TITLE
Osx not working

### ISSUE THREAD

**Issue by goors** [jpetazzo/pipework#99]
It would be great if pipework can work on mac.
I am getting error: 

<pre>
./pipework: line 81: /proc/mounts: No such file or directory
Could not locate cgroup mount point.
</pre>

I tried creating  /proc/mounts but that leaves me with:

<pre>
Could not locate cgroup mount point.
</pre>

Is there any way pipework can work on OSX?

**Comment by jpetazzo** [comment]
No, it won't work on OS X, because pipework relies on the fact that it runs on the same kernel as your Docker containers; which is not the case on OS X. On OS X, Docker runs within a VM, and you want to run pipework on that VM. Sorry!

**Comment by brockbackups** [comment]
any changes on this since Docker for mac is no longer in a VM running on boot2docker?

**Comment by jpetazzo** [comment]
No, unfortunately, pipework is probably never going to work on a Mac. Sorry!
